name: Build HTML [using jupyter-book]
on: [pull_request]
jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
      - name: Install required libraries
        shell: bash -l {0}
        run: |
          pip install pyodide-py jupytext PyYAML
      # Soft check on CI to check the WASM compatibility.
      - name: Check WASM lectures
        shell: bash -l {0}
        run: |
          python testing/check_wasm.py
